ElectricPineapple/ElectricPineapple/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectricPineapple;
using System.Security.Claims;
using Microsoft.AspNet.Identity;

namespace ElectricPineapple.Controllers
{
    public class EventController : Controller
    {
        private CVGSEntities db = new CVGSEntities();


        // GET: Event
        public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        // GET: Event/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        [HttpPost]
        public ActionResult Details()
        {
            int? id = int.Parse(Request["eventID"]);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            var userId = User.Identity.GetUserId();
            CVGSUser user = db.CVGSUsers.Where(u => u.userLink == userId).First();

            @event.CVGSUsers.Add(user);
            user.Events.Add(@event);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        // GET: Event/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Event/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "eventID,name,description,startTime,endTime")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@event);
        }

        // GET: Event/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Event/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "eventID,name,description,startTime,endTime")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Event/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElectricPineapple/ElectricPineapple/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectricPineapple;
using System.IO;

namespace ElectricPineapple.Controllers
{      
    public class HomeController : Controller
    {
        private CVGSEntities db = new CVGSEntities();

        public ActionResult Index()
        {
            var news = db.News.Take(10);
            ViewData["NewsList"] = news.ToList();

            var events = db.Events.Take(10);
            ViewData["EventList"] = events.ToList();


            var games = db.Games.Where(n => n.releaseDate > DateTime.Now).Take(10).OrderBy(g => g.releaseDate);
            return View(games.ToList());
        }

        public ActionResult GameCatalogue()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult NewPageTemplate()
        {
            return View();
        }
        public ActionResult Game()
        {
            return View();
        }
    }
}

ElectricPineapple/ElectricPineapple/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectricPineapple;

namespace ElectricPineapple.Controllers
{
    public class NewsController : Controller
    {
        private CVGSEntities db = new CVGSEntities();

        // GET: News
        public ActionResult Index()
        {
            return View(db.News.ToList());
        }

        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: News/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "newsID,Title,Description")] News news)
        {
            if (ModelState.IsValid)
            {
                db.News.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(news);
        }

        // GET: News/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "newsID,Title,Description")] News news)
        {
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        // GET: News/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = db.News.Find(id);
            db.News.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElectricPineapple/ElectricPineapple/Views/Home/About.cshtml
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">About Electric Pineapple</h1>
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <p>Use this area to provide additional information.</p>
    </div>
</div>

ElectricPineapple/ElectricPineapple/Views/Home/Contact.cshtml
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Contact Electric Pineapple</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <address>
            One Microsoft Way<br />
            Redmond, WA 98052-6399<br />
            <abbr title="Phone">P:</abbr>
            425.555.0100
        </address>

        <address>
            <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
            <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
        </address>
    </div>
</div>

ElectricPineapple/ElectricPineapple/Views/Home/Game.cshtml
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Batman Arkham Asylum</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default panel-center">
            <div class="panel-heading">
                <h3 class="panel-title">Batman Arkham Asylum</h3>
            </div>
            <div class="panel-body">
                    <img src="~/Content/images/batmanScreenshot.jpg"/>
                    <span class="panel-game-details">
                        $69.99<br /><br />
                        PC Horror<br /><br />
                        Action<br/><br/>
                        Experience what it’s like to be Batman and face off against Gotham's greatest villians. Explore every inch of Arkham Asylum and roam freely on the infamous island. Batman punches the living shit outta some god damn bad guys. <br /><br />
                        <input class="btn btn-add-to-cart" type="button" value="Add To Cart" /><br /><br/>
                        <input class="btn btn-add-to-wishlist" type="button" value="Add To Wishlist" />
                    </span>
             </div>
         </div>
    </div>
</div>

ElectricPineapple/ElectricPineapple/Views/Home/Index.cshtml
@model IEnumerable<ElectricPineapple.Game>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div id="myCarousel" class="carousel slide" style="margin-left: 15px; width:98.15%;" data-ride=" carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="~/Content/images/bf4.jpg" alt="Battlefield 4">
            </div>

            <div class="item">
                <img src="~/Content/images/assasins.jpg" alt="Assassins Creed">
            </div>

            <div class="item">
                <img src="~/Content/images/Batman.jpg" alt="NANANANANANANANAN BATMAN">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
<br />
<div class="row">
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-comments fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">26</div>
                        <div>New Games!</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Index","Game")">
                <div class="panel-footer-top">
                    <span class="pull-left">View New Releases</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-tasks fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">12</div>
                        <div>New Events!</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Index","Event")">
                <div class="panel-footer-top">
                    <span class="pull-left">View Upcoming Events!</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-tasks fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">8</div>
                        <div>News Stories!</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Index","News")">
                <div class="panel-footer-top">
                    <span class="pull-left">View News Stories</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-8">
        <!-- /.panel -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> @Html.ActionLink("News", "Index", "News")

            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                @{var NewsItems = (List<News>)ViewData["NewsList"];}
                @foreach (var item in NewsItems)
                {
                    <table>
                        <tr>
                            <td>
                                @Html.ActionLink(item.Title, "Details", "News", new { id = item.newsID }, new { @style = "color:#000000;" })<br />
                                <p> - @Html.ActionLink(item.Description, "Details", "News", new { id = item.newsID }, new { @style = "color:#FFFFF;" })</p>
                            </td>
                        </tr>
                    </table>
                }
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-clock-o fa-fw"></i> @Html.ActionLink("Upcoming Events", "Index", "Event")
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Event Name</th>
                                <th>Release Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{var events = (List<Event>)ViewData["EventList"];
                            foreach (var item in events)
                            {
                                <tr>
                                    <td>
                                        @Html.ActionLink(item.name, "Details", "Event", new { id = item.eventID }, new { @style = "color:#000000;" })
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.description)
                                    </td>
                                </tr>
                            }}
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel -->
        </div>
    </div>

    <!-- /.col-lg-8 -->
    <div class="row">
        <div class="col-lg-4">
            <!-- /.panel -->
            <!-- /.panel -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-clock-o fa-fw"></i> Top Rated Games
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Game</th>
                                    <th>Rating</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>3326</td>
                                    <td>Metal Gear Solid V: The Phantom Pain</td>
                                    <td>10/10</td>
                                </tr>
                                <tr>
                                    <td>3325</td>
                                    <td>Fallout 4</td>
                                    <td>9.5/10</td>
                                </tr>
                                <tr>
                                    <td>3324</td>
                                    <td>Rise of the Tomb Raider</td>
                                    <td>9.3/10</td>
                                </tr>
                                <tr>
                                    <td>3323</td>
                                    <td>Call of Duty: Black Ops III</td>
                                    <td>9.2/10</td>
                                </tr>
                                <tr>
                                    <td>3322</td>
                                    <td>Divinity: Original Sin - Enhanced Edition</td>
                                    <td>9/10</td>
                                </tr>
                                <tr>
                                    <td>3321</td>
                                    <td>Halo 5: Guardians</td>
                                    <td>9/10</td>
                                </tr>
                                <tr>
                                    <td>3320</td>
                                    <td>Forza Motorsport 6</td>
                                    <td>9/10</td>
                                </tr>
                                <tr>
                                    <td>3319</td>
                                    <td>WWE 2K16</td>
                                    <td>8.8/10</td>
                                </tr>
                                <tr>
                                    <td>3318</td>
                                    <td>Rock Band 4</td>
                                    <td>8.8/10</td>
                                </tr>
                                <tr>
                                    <td>3317</td>
                                    <td>Gears of War: Ultimate Edition</td>
                                    <td>8.5/10</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->

            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-clock-o fa-fw"></i> @Html.ActionLink("Upcoming Games", "Index", "Game")
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>Game</th>
                                    <th>Release Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.ActionLink(item.title, "Details", "Game", new { id = item.gameID }, new { @style = "color:#000000;" })
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.releaseDate)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                </div>
                    <!-- /.panel body -->
                    <!-- /.panel -->


                </div>
            </div>
        <!-- /.col-lg-4 -->
    </div>

ElectricPineapple/ElectricPineapple/Views/Home/NewPageTemplate.cshtml
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <p>I sexually Identify as an Attack Helicopter. Ever since I was a boy I dreamed of soaring over the oilfields dropping hot sticky loads on disgusting foreigners. People say to me that a person being a helicopter is Impossible and I'm fucking retarded but I don't care, I'm beautiful. I'm having a plastic surgeon install rotary blades, 30 mm cannons and AMG-114 Hellfire missiles on my body. From now on I want you guys to call me "Apache" and respect my right to kill from above and kill needlessly. If you can't accept me you're a heliphobe and need to check your vehicle privilege. Thank you for being so understanding.</p>
    </div>
</div>