ElectricPineapple/ElectricPineapple/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectricPineapple;
using System.IO;
using System.Security.Claims;
using Microsoft.AspNet.Identity;

namespace ElectricPineapple.Controllers
{
    public class GameController : Controller
    {
        private CVGSEntities db = new CVGSEntities();

        // GET: Game
        public ActionResult Index()
        {
            var games = db.Games.Include(g => g.ESRBRating1).Include(g => g.Publisher1).Include(g => g.Platform1).Include(g => g.Genre1);
            return View(games.ToList());
        }

        // GET: Game/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }

            //Create a list of game ratings for that game
            List<Rating> gameRatings = new List<Rating>();
            gameRatings = db.Ratings.Where(r => r.gameID == id).ToList();

            if (gameRatings.Count() > 0)
            {
                var gameRating = 0;

                foreach (Rating item in gameRatings)
                {
                    gameRating += item.rating1;
                }
                //Get an average for game ratings
                gameRating = gameRating / gameRatings.Count();

                ViewData["GameRating"] = "Game rating: " + gameRating + "/10";
                ViewData["RatingList"] = gameRatings;
            }
            else
            {
                //If no ratings, just display "no ratings"
                ViewData["GameRating"] = "Game has no ratings";
                ViewData["RatingList"] = null;
            }

            return View(game);
        }

        [HttpPost]
        public ActionResult Details()
        {
            int? id = int.Parse(Request["gameID"]);
            int rating = int.Parse(Request["gameRating"]);
            string reviewText = Request["reviewText"];

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }

            //Gets user ID
            var userId = User.Identity.GetUserId();
            CVGSUser user = db.CVGSUsers.Where(u => u.userLink == userId).First();

            Rating userRating = null;

            //If the user already has a rating for the game, update that rating
            try
            {
                userRating = db.Ratings.Where(a => a.gameID == id && a.userID == user.userID).First();
            }
            catch
            {            
            }

            if (userRating == null)
            {
                //If the user has not yet rated that game, add a new rating to database
                userRating = new Rating();
                user.Ratings.Add(userRating);
                game.Ratings.Add(userRating);
            }            

            //Set rating
            userRating.rating1 = rating;
            userRating.review = reviewText;
            
            db.SaveChanges();

            TempData["message"] = "Rating added successfully!";

            return RedirectToAction("Details", new { id = id });
        }

        [HttpPost]
        public ActionResult AddToWishList()
        {
            int id = int.Parse(Request["gameID"]);
            Game game = db.Games.Find(id);

            //Gets user ID
            var userId = User.Identity.GetUserId();
            CVGSUser user = db.CVGSUsers.Where(u => u.userLink == userId).First();

            Game_User gameUser = null;

            //Check if item is already on wishlist
            try
            {
                gameUser = db.Game_User.Where(a => a.gameID == id && a.userID == user.userID).First();
            }
            catch
            {
            }

            if (gameUser == null)
            {
                //Otherwise add connection
                gameUser = new Game_User();
                gameUser.status = 2;
                user.Game_User.Add(gameUser);
                game.Game_User.Add(gameUser);
                db.SaveChanges();
                TempData["message"] = ("Added to wishlist.");
            }
            else
            {
                TempData["message"] = ("Game already in wishlist.");
            }  
            return RedirectToAction("Details", new { id = id });
        }

        [HttpPost]
        public ActionResult AddToCart()
        {
            int id = int.Parse(Request["gameID"]);
            Game game = db.Games.Find(id);

            //Gets user ID
            var userId = User.Identity.GetUserId();
            CVGSUser user = db.CVGSUsers.Where(u => u.userLink == userId).First();

            Order order = null;          

            try
            {
                //Will search for a cart from the user that has not been checked out
                order = db.Orders.Where(a => a.status == "1" && a.userID == user.userID).First();
            }
            catch
            {
            }

            //If user does not have an open cart, create a new one
            if (order == null)
            {
                order = new Order();
                //Status code 1 is for carts in progress
                order.status = "1";
                order.date = DateTime.Now;
                //Sets the cart to belong to the user
                order.CVGSUser = user;
                user.Orders.Add(order);
            }
            //Add the game to the cart
            order.Games.Add(game);
            db.SaveChanges();                                               

            return RedirectToAction("ViewCart", "Account");
        }

        [Authorize(Roles="Admin")]
        public ActionResult ApproveReview(int? userID, int? gameID)
        {
            //Get the rating and set it to approved
            Rating rating = db.Ratings.Where(a => a.userID == userID && a.gameID == gameID).FirstOrDefault();
            rating.approved = 1;
            db.SaveChanges();

            //Go back to same page
            return RedirectToAction("Details", new { id = rating.gameID });
        }

        // GET: Game/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.ESRBRating = new SelectList(db.ESRBRatings, "ratingID", "rating");
            ViewBag.publisher = new SelectList(db.Publishers, "publisherID", "publisher1");
            ViewBag.platform = new SelectList(db.Platforms, "platformID", "platform1");
            ViewBag.genre = new SelectList(db.Genres, "genreID", "genre1");
            return View();
        }

        // POST: Game/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "gameID,title,genre,publisher,ESRBRating,releaseDate,price,description,platform")] Game game, HttpPostedFileBase gameCover, HttpPostedFileBase gameScreenshot)
        {
            if (ModelState.IsValid)
            {
                if (gameCover != null)
                {
                    //If filename is too long, shorten it
                    var fileName = Path.GetFileName(gameCover.FileName);
                    if(fileName.Length > 60)
                    {
                        fileName = fileName.Substring(0, 55) + fileName.Substring(fileName.Length - 5, 5);
                    }

                    var path = Path.Combine(Server.MapPath("~/Content/images/box covers"), fileName);
                    gameCover.SaveAs(path);
                    game.coverPath = fileName;
                }
                //Saves image files, then saves their path in database
                if (gameScreenshot != null)
                {
                    var fileName = Path.GetFileName(gameScreenshot.FileName);
                    if (fileName.Length > 60)
                    {
                        fileName = fileName.Substring(0, 55) + fileName.Substring(fileName.Length - 5, 5);
                    }
                    var path = Path.Combine(Server.MapPath("~/Content/images/screenshots"), fileName);
                    gameScreenshot.SaveAs(path);
                    game.screenshotPath = fileName;
                }

                db.Games.Add(game);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ESRBRating = new SelectList(db.ESRBRatings, "ratingID", "rating", game.ESRBRating);
            ViewBag.publisher = new SelectList(db.Publishers, "publisherID", "publisher1", game.publisher);
            ViewBag.platform = new SelectList(db.Platforms, "platformID", "platform1", game.platform);
            ViewBag.genre = new SelectList(db.Genres, "genreID", "genre1", game.genre);
            return View(game);
        }

        // GET: Game/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            ViewBag.ESRBRating = new SelectList(db.ESRBRatings, "ratingID", "rating", game.ESRBRating);
            ViewBag.publisher = new SelectList(db.Publishers, "publisherID", "publisher1", game.publisher);

ElectricPineapple/ElectricPineapple/Controllers/PublisherController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectricPineapple;
using System.IO;

namespace ElectricPineapple.Controllers
{
    public class PublisherController : Controller
    {
        private CVGSEntities db = new CVGSEntities();

        // GET: Publisher
        public ActionResult Index()
        {
            return View(db.Publishers.ToList());
        }

        // GET: Publisher/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publisher publisher = db.Publishers.Find(id);
            if (publisher == null)
            {
                return HttpNotFound();
            }

            var games = db.Games.Include(g => g.ESRBRating1).Include(g => g.Publisher1).Include(g => g.Platform1).Include(g => g.Genre1).Where(n => n.Publisher1.publisherID == publisher.publisherID);
            ViewData["publisherGames"] = games.ToList();

            return View(publisher);
        }

        // GET: Publisher/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Publisher/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "publisherID,publisher1")] Publisher publisher, HttpPostedFileBase publisherImage)
        {
            if (ModelState.IsValid)
            {
                if (publisherImage != null)
                {
                    //Shortens filename if too long
                    var fileName = Path.GetFileName(publisherImage.FileName);
                    if (fileName.Length > 30)
                    {
                        fileName = fileName.Substring(0, 25) + fileName.Substring(fileName.Length - 5, 5);
                    }
                    var path = Path.Combine(Server.MapPath("~/Content/images/publishers"), fileName);
                    publisherImage.SaveAs(path);
                    publisher.imagePath = fileName;
                }

                db.Publishers.Add(publisher);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(publisher);
        }

        // GET: Publisher/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publisher publisher = db.Publishers.Find(id);
            if (publisher == null)
            {
                return HttpNotFound();
            }
            return View(publisher);
        }

        // POST: Publisher/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "publisherID,publisher1")] Publisher publisher, HttpPostedFileBase publisherImage)
        {
            if (ModelState.IsValid)
            {
                var currentPublisher = db.Publishers.Where(p => p.publisherID == publisher.publisherID).First();
                if (currentPublisher == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    currentPublisher.publisher1 = publisher.publisher1;
                }

                if(publisherImage != null)
                {
                    //Shortens filename if too long
                    var fileName = Path.GetFileName(publisherImage.FileName);
                    if (fileName.Length > 30)
                    {
                        fileName = fileName.Substring(0, 25) + fileName.Substring(fileName.Length - 5, 5);
                    }
                    var path = Path.Combine(Server.MapPath("~/Content/images/publishers"), fileName);
                    publisherImage.SaveAs(path);
                    currentPublisher.imagePath = fileName;
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(publisher);
        }

        // GET: Publisher/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publisher publisher = db.Publishers.Find(id);
            if (publisher == null)
            {
                return HttpNotFound();
            }
            return View(publisher);
        }

        // POST: Publisher/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Publisher publisher = db.Publishers.Find(id);
            db.Publishers.Remove(publisher);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElectricPineapple/ElectricPineapple/Views/Publisher/Create.cshtml
@model ElectricPineapple.Publisher

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Create</h1>
    </div>
</div>

@using (Html.BeginForm("Create", "Publisher", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Publisher</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.publisher1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.publisher1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.publisher1, "", new { @class = "text-danger" })
            </div>

                <label for="file">Upload Publisher Image:</label>
                <input type="file" name="publisherImage" id="publisherImage" /><br><br>
            </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ElectricPineapple/ElectricPineapple/Views/Publisher/Delete.cshtml
@model ElectricPineapple.Publisher

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Delete</h1>
    </div>
</div>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Publisher</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.publisher1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.publisher1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ElectricPineapple/ElectricPineapple/Views/Publisher/Details.cshtml
@model ElectricPineapple.Publisher

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Details</h1>
    </div>
</div>

<div>
    <h4>Publisher</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.publisher1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.publisher1)
        </dd>

        <dd>
            <img src="~/Content/images/publishers/@Model.imagePath" width="800" height="450" />
        </dd>

    </dl>
</div>
<p>
    @if(User.IsInRole("Admin"))
    { 
    @Html.ActionLink("Edit", "Edit", new { id = Model.publisherID }); @: | 
    @Html.ActionLink("Back to List", "Index");
    }
</p>
@*Show a listing of all the publisher's games*@

@{int i = 0;
var publisherGames = (List<Game>)ViewData["publisherGames"];}
@foreach (var item in publisherGames)
{
    if (i == 0)
    {
        @:<div class="row">
            @:<div class="col-lg-12">
	}

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href=@Url.Action("Details", "Game", new {id = item.gameID})>
                    <h3 class="panel-title">@item.title</h3>
                </a>
            </div>
            <div class="panel-body">
                <a href=@Url.Action("Details", "Game", new {id = item.gameID})>
                    <img src="~/Content/images/box covers/@item.coverPath" width="155" height="220" />
                </a>
                <span class="panel-game-info">
                    $@item.price<br /><br />
                    @item.Publisher1.publisher1<br /><br />
                    @item.Platform1.platform1, @item.Genre1.genre1<br /><br />
                    @if (item.description.Length < 95)
                    {
                        @item.description<br /><br />
                    }
                    else
                    {
                        @item.description.Substring(0, 95);
                        @:...<br /><br />
                        }
                </span>
                <br /><br />
                <input class="btn btn-add-to-cart" type="button" value="Add To Cart" />
            </div>
        </div>
    </div>

                    i++;
                    if (i == 4)
                    {
                        i = 0;
                        @:</div>
                        @:</div>
                    }

}
@if (i != 0)
{
    @:</div>
    @:</div>
}

ElectricPineapple/ElectricPineapple/Views/Publisher/Edit.cshtml
@model ElectricPineapple.Publisher

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Edit</h1>
    </div>
</div>

@using (Html.BeginForm("Edit", "Publisher", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Publisher</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.publisherID)

        <div class="form-group">
            @Html.LabelFor(model => model.publisher1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.publisher1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.publisher1, "", new { @class = "text-danger" })
            </div>

            <label for="file">Upload Publisher Image:</label>
            <input type="file" name="publisherImage" id="publisherImage" /><br><br>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ElectricPineapple/ElectricPineapple/Views/Publisher/Index.cshtml
@model IEnumerable<ElectricPineapple.Publisher>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Publishers</h1>
    </div>
</div>
@if(User.IsInRole("Admin"))
{ 
    @Html.ActionLink("Create New", "Create");
}

@*Show cards for each publisher*@
@{int i = 0;}
@foreach (var item in Model)
{
    if (i == 0)
    {
        @:<div class="row">
        @:<div class="col-lg-12">
	}

        <div class="col-md-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href=@Url.Action("Details", "Publisher", new {id = item.publisherID})>
                        <h3 class="panel-title">@item.publisher1</h3>
                    </a>
                </div>
                <div class="panel-body">
                    <a href=@Url.Action("Details", "Publisher", new {id = item.publisherID})>
                        <img src="~/Content/images/publishers/@item.imagePath" width="200" height="220" />
                    </a>
                </div>
            </div>
        </div>

        i++;
        if (i == 6)
        {
            i = 0;
            @:</div>
            @:</div>
        }

}
@if (i != 0)
{
    @:</div>
    @:</div>
}