ElectricPineapple/ElectricPineapple/Controllers/CVGSUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectricPineapple;
using System.Security.Claims;
using Microsoft.AspNet.Identity;

namespace ElectricPineapple.Controllers
{
    public class CVGSUsersController : Controller
    {
        private CVGSEntities db = new CVGSEntities();

        // GET: CVGSUsers
        public ActionResult Index()
        {
            var cVGSUsers = db.CVGSUsers.Include(c => c.Province1).Include(c => c.UserType1);
            return View(cVGSUsers.ToList());
        }

        // GET: CVGSUsers/Details/5
        public ActionResult Details(int? id)
        {
            var userId = User.Identity.GetUserId();
            CVGSUser user = db.CVGSUsers.Where(u => u.userLink == userId).First();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CVGSUser cVGSUser = db.CVGSUsers.Find(id);
            if (cVGSUser == null)
            {
                return HttpNotFound();
            }

            //Creates a list of games that are on the users wishlist
            List<Game> wishlist = new List<Game>();
            foreach (Game_User item in db.Game_User)
            {
                if (item.CVGSUser == cVGSUser)
                {
                    wishlist.Add(item.Game);
                }
            }

            bool friends = false;
            //If the users are friends, or the user is viewing their own profile, show the wishlist (on view)
            if(db.Friends.Where(b => b.UserID == user.userID && b.FriendID == cVGSUser.userID).Count() > 0 || id == user.userID)
            {
                friends = true;
            }

            ViewData["userWishlist"] = wishlist;
            ViewData["areFriends"] = friends;

            return View(cVGSUser);
        }

        // GET: CVGSUsers/Create
        public ActionResult Create()
        {
            ViewBag.province = new SelectList(db.Provinces, "provinceCode", "province1");
            ViewBag.userType = new SelectList(db.UserTypes, "typeID", "typeID");
            return View();
        }

        // POST: CVGSUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "userID,firstName,lastName,userName,email,address,city,province,phone,password,gender,recievePromotions,profileInfo,userType,userLink")] CVGSUser cVGSUser)
        {
            if (ModelState.IsValid)
            {
                db.CVGSUsers.Add(cVGSUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.province = new SelectList(db.Provinces, "provinceCode", "province1", cVGSUser.province);
            ViewBag.userType = new SelectList(db.UserTypes, "typeID", "typeID", cVGSUser.userType);
            return View(cVGSUser);
        }

        // GET: CVGSUsers/Edit/5
        [Authorize(Roles="Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CVGSUser cVGSUser = db.CVGSUsers.Find(id);
            if (cVGSUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.province = new SelectList(db.Provinces, "provinceCode", "province1", cVGSUser.province);
            ViewBag.userType = new SelectList(db.UserTypes, "typeID", "typeID", cVGSUser.userType);
            return View(cVGSUser);
        }

        // POST: CVGSUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "userID,firstName,lastName,userName,email,address,city,province,phone,password,gender,recievePromotions,profileInfo,userType,userLink")] CVGSUser cVGSUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cVGSUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.province = new SelectList(db.Provinces, "provinceCode", "province1", cVGSUser.province);
            ViewBag.userType = new SelectList(db.UserTypes, "typeID", "typeID", cVGSUser.userType);
            return View(cVGSUser);
        }

        // GET: CVGSUsers/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CVGSUser cVGSUser = db.CVGSUsers.Find(id);
            if (cVGSUser == null)
            {
                return HttpNotFound();
            }
            return View(cVGSUser);
        }

        // POST: CVGSUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CVGSUser cVGSUser = db.CVGSUsers.Find(id);
            db.CVGSUsers.Remove(cVGSUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SearchResults(string SearchText)
        {
            //Search for a user
            ViewData["SearchTerm"] = SearchText;
            var users = db.CVGSUsers.Where(a => a.userName.Contains(SearchText) || a.email.Contains(SearchText));
            return View(users.ToList());
        }

        //[HttpPost]
        public ActionResult AddFriend(int? id)
        {
            CVGSUser friend = db.CVGSUsers.Find(id);

            var userId = User.Identity.GetUserId();
            CVGSUser user = db.CVGSUsers.Where(u => u.userLink == userId).First();

            //Links the two users
            Friend newfriendship = new Friend();
            newfriendship.FriendID = friend.userID;
            newfriendship.UserID = user.userID;
            db.Friends.Add(newfriendship);
            
            db.SaveChanges();

            var AllFriends = db.Friends.Where(a => a.UserID == user.userID);

            List<CVGSUser> friends = new List<CVGSUser>();
            //Gets a list of all the users friends
            foreach (Friend item in AllFriends)
            {
                friends.Add(db.CVGSUsers.Find(item.FriendID));
            }
            
            return View("FriendsList", friends.ToList());
        }

        public ActionResult FriendsList()
        {
            var userId = User.Identity.GetUserId();
            CVGSUser user = db.CVGSUsers.Where(u => u.userLink == userId).First();

            var AllFriends = db.Friends.Where(a => a.UserID == user.userID).Distinct<Friend>();

            List<CVGSUser> friends = new List<CVGSUser>();
            //Creates a list of all the users friends
            foreach (Friend item in AllFriends)
            {
                friends.Add(db.CVGSUsers.Find(item.FriendID));
            }

            return View(friends.ToList());
        }
    }
}

ElectricPineapple/ElectricPineapple/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectricPineapple;
using System.IO;
using System.Security.Claims;
using Microsoft.AspNet.Identity;

namespace ElectricPineapple.Controllers
{
    public class GameController : Controller
    {
        private CVGSEntities db = new CVGSEntities();

        // GET: Game
        public ActionResult Index()
        {
            var games = db.Games.Include(g => g.ESRBRating1).Include(g => g.Publisher1).Include(g => g.Platform1).Include(g => g.Genre1);
            return View(games.ToList());
        }

        // GET: Game/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }

            //Create a list of game ratings for that game
            List<Rating> gameRatings = new List<Rating>();
            gameRatings = db.Ratings.Where(r => r.gameID == id).ToList();

            if (gameRatings.Count() > 0)
            {
                var gameRating = 0;

                foreach (Rating item in gameRatings)
                {
                    gameRating += item.rating1;
                }
                //Get an average for game ratings
                gameRating = gameRating / gameRatings.Count();

                ViewData["GameRating"] = "Game rating: " + gameRating + "/10";
                ViewData["RatingList"] = gameRatings;
            }
            else
            {
                //If no ratings, just display "no ratings"
                ViewData["GameRating"] = "Game has no ratings";
                ViewData["RatingList"] = null;
            }

            return View(game);
        }

        [HttpPost]
        public ActionResult Details()
        {
            int? id = int.Parse(Request["gameID"]);
            int rating = int.Parse(Request["gameRating"]);
            string reviewText = Request["reviewText"];

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }

            //Gets user ID
            var userId = User.Identity.GetUserId();
            CVGSUser user = db.CVGSUsers.Where(u => u.userLink == userId).First();

            Rating userRating = null;

            //If the user already has a rating for the game, update that rating
            try
            {
                userRating = db.Ratings.Where(a => a.gameID == id && a.userID == user.userID).First();
            }
            catch
            {            
            }

            if (userRating == null)
            {
                //If the user has not yet rated that game, add a new rating to database
                userRating = new Rating();
                user.Ratings.Add(userRating);
                game.Ratings.Add(userRating);
            }            

            //Set rating
            userRating.rating1 = rating;
            userRating.review = reviewText;
            
            db.SaveChanges();

            TempData["message"] = "Rating added successfully!";

            return RedirectToAction("Details", new { id = id });
        }

        [HttpPost]
        public ActionResult AddToWishList()
        {
            int id = int.Parse(Request["gameID"]);
            Game game = db.Games.Find(id);

            //Gets user ID
            var userId = User.Identity.GetUserId();
            CVGSUser user = db.CVGSUsers.Where(u => u.userLink == userId).First();

            Game_User gameUser = null;

            //Check if item is already on wishlist
            try
            {
                gameUser = db.Game_User.Where(a => a.gameID == id && a.userID == user.userID).First();
            }
            catch
            {
            }

            if (gameUser == null)
            {
                //Otherwise add connection
                gameUser = new Game_User();
                gameUser.status = 2;
                user.Game_User.Add(gameUser);
                game.Game_User.Add(gameUser);
                db.SaveChanges();
                TempData["message"] = ("Added to wishlist.");
            }
            else
            {
                TempData["message"] = ("Game already in wishlist.");
            }  
            return RedirectToAction("Details", new { id = id });
        }

        [HttpPost]
        public ActionResult AddToCart()
        {
            int id = int.Parse(Request["gameID"]);
            Game game = db.Games.Find(id);

            //Gets user ID
            var userId = User.Identity.GetUserId();
            CVGSUser user = db.CVGSUsers.Where(u => u.userLink == userId).First();

            Order order = null;          

            try
            {
                //Will search for a cart from the user that has not been checked out
                order = db.Orders.Where(a => a.status == "1" && a.userID == user.userID).First();
            }
            catch
            {
            }

            //If user does not have an open cart, create a new one
            if (order == null)
            {
                order = new Order();
                //Status code 1 is for carts in progress
                order.status = "1";
                order.date = DateTime.Now;
                //Sets the cart to belong to the user
                order.CVGSUser = user;
                user.Orders.Add(order);
            }
            //Add the game to the cart
            order.Games.Add(game);
            db.SaveChanges();                                               

            return RedirectToAction("ViewCart", "Account");
        }

        [Authorize(Roles="Admin")]
        public ActionResult ApproveReview(int? userID, int? gameID)
        {
            //Get the rating and set it to approved
            Rating rating = db.Ratings.Where(a => a.userID == userID && a.gameID == gameID).FirstOrDefault();
            rating.approved = 1;
            db.SaveChanges();

            //Go back to same page
            return RedirectToAction("Details", new { id = rating.gameID });
        }

        // GET: Game/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.ESRBRating = new SelectList(db.ESRBRatings, "ratingID", "rating");
            ViewBag.publisher = new SelectList(db.Publishers, "publisherID", "publisher1");
            ViewBag.platform = new SelectList(db.Platforms, "platformID", "platform1");
            ViewBag.genre = new SelectList(db.Genres, "genreID", "genre1");
            return View();
        }

        // POST: Game/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "gameID,title,genre,publisher,ESRBRating,releaseDate,price,description,platform")] Game game, HttpPostedFileBase gameCover, HttpPostedFileBase gameScreenshot)
        {
            if (ModelState.IsValid)
            {
                if (gameCover != null)
                {
                    //If filename is too long, shorten it
                    var fileName = Path.GetFileName(gameCover.FileName);
                    if(fileName.Length > 60)
                    {
                        fileName = fileName.Substring(0, 55) + fileName.Substring(fileName.Length - 5, 5);
                    }

                    var path = Path.Combine(Server.MapPath("~/Content/images/box covers"), fileName);
                    gameCover.SaveAs(path);
                    game.coverPath = fileName;
                }
                //Saves image files, then saves their path in database
                if (gameScreenshot != null)
                {
                    var fileName = Path.GetFileName(gameScreenshot.FileName);
                    if (fileName.Length > 60)
                    {
                        fileName = fileName.Substring(0, 55) + fileName.Substring(fileName.Length - 5, 5);
                    }
                    var path = Path.Combine(Server.MapPath("~/Content/images/screenshots"), fileName);
                    gameScreenshot.SaveAs(path);
                    game.screenshotPath = fileName;
                }

                db.Games.Add(game);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ESRBRating = new SelectList(db.ESRBRatings, "ratingID", "rating", game.ESRBRating);
            ViewBag.publisher = new SelectList(db.Publishers, "publisherID", "publisher1", game.publisher);
            ViewBag.platform = new SelectList(db.Platforms, "platformID", "platform1", game.platform);
            ViewBag.genre = new SelectList(db.Genres, "genreID", "genre1", game.genre);
            return View(game);
        }

        // GET: Game/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            ViewBag.ESRBRating = new SelectList(db.ESRBRatings, "ratingID", "rating", game.ESRBRating);
            ViewBag.publisher = new SelectList(db.Publishers, "publisherID", "publisher1", game.publisher);

ElectricPineapple/ElectricPineapple/Views/Game/Create.cshtml
@model ElectricPineapple.Game

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Create</h1>
    </div>
</div>

    @using (Html.BeginForm("Create", "Game", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Game</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.genre, "genre", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("genre", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.genre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.publisher, "publisher", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("publisher", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.publisher, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ESRBRating, "ESRBRating", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ESRBRating", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ESRBRating, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.releaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.releaseDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.releaseDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.platform, "platform", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("platform", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.platform, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label for="file">Upload Box Cover Image:</label>
                <input type="file" name="gameCover" id="gameCover" /><br><br>

                <label for="file">Upload Game Screenshot:</label>
                <input type="file" name="gameScreenshot" id="gameScreenshot" /><br><br>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

ElectricPineapple/ElectricPineapple/Views/Game/Details.cshtml
@model ElectricPineapple.Game

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Details</h1>
    </div>
</div>

<div>
    @*Shows whether item was added to wishlist successfully or not*@
    @TempData["message"]
</div>
<p>
@if (User.IsInRole("Admin"))
{ 
    @Html.ActionLink("Edit", "Edit", new { id = Model.gameID }); @: | 
    @Html.ActionLink("Back to List", "Index");
}
</p>

<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default panel-center">
            <div class="panel-heading">
                <h3 class="panel-title">@Model.title</h3>
            </div>
            <div class="panel-body">
                <div id="myCarousel" class="carousel slide" style="height: 500px; width:800px; position:absolute" data-ride=" carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="~/Content/images/screenshots/@Model.screenshotPath" height="500" width="800"/>
                        </div>

                        <div class="item">
                            <img src="~/Content/images/screenshots/@Model.screenshotPath" />
                        </div>

                        <div class="item">
                            <img src="~/Content/images/screenshots/@Model.screenshotPath" />
                        </div>
                    </div>

                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <span class="panel-game-details">
                    @*Shows the games info*@
                    <img src="~/Content/images/publishers/@Model.Publisher1.imagePath" width="250" height="250" />
                    $@Model.price<br /><br />
                    @ViewData["GameRating"] <br /><br />
                    @Model.Platform1.platform1, @Model.Genre1.genre1<br /><br />
                    @Model.Publisher1.publisher1 <br /><br />
                    @Model.description<br /><br />

                    @*If user is logged in, allow them to add to cart or wishlist*@
                    @if (Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("AddToCart", "Game", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.HiddenFor(model => model.gameID)
                            <input class="btn btn-add-to-wishlist" type="submit" value="Add To Cart" /><br/><br/>
                        }
                        using (Html.BeginForm("AddToWishList", "Game", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.HiddenFor(model => model.gameID)
                            <input class="btn btn-add-to-wishlist" type="submit" value="Add To Wishlist" />
                        }
                    }
                </span>
            </div>
        </div>
        @*If user is logged in, allow them to leave a rating/review*@
        @if (Request.IsAuthenticated)
        {
            using (Html.BeginForm("Details", "Game", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="row">
                    <div class="col-md-8">
                        <div class="panel panel-default panel-center">
                            <div class="panel-heading">
                                <h3 class="panel-title">@Model.title</h3>
                            </div>
                            <div class="panel-body">

                                @Html.HiddenFor(model => model.gameID)
                                <p>Review this game!</p>
                                <p>Leave a rating out of 10</p>

                                <select id="gameRating" name="gameRating" class="form-control">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                </select>

                                <p>(Optional) Leave a review to explain your rating:</p>
                                <textarea id="reviewText" name="reviewText" class="form-control"></textarea><br />

                                <input type="submit" value="Submit" class="form-control" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        }

    @if (ViewData["RatingList"] != null)
    {
        <br/>
        @*If user is an admin, show all unapproved reviews, with a button to approve them*@
        if (User.IsInRole("Admin"))
        {
            foreach (Rating item in (List<Rating>)ViewData["RatingList"])
            {                
                    <div class="row">
                        <div class="col-md-8">
                            <div class="panel panel-default panel-center">
                                <div class="panel-heading">
                                    <a href="@Url.Action("Details", "CVGSUsers", new { id = item.CVGSUser.userID})">
                                        <h3 class="panel-title">@item.CVGSUser.userName</h3>
                                    </a>
                                </div>
                                <div class="panel-body">
                                    Rating: @item.rating1/10
                                    @if (item.review != null)
                                    {
                                        <br />
                                        @item.review
                                    }
                                    @if (item.approved == 0)
                                    { 
                                        using (Html.BeginForm("ApproveReview", "Game"))
                                        {
                                            <input type="hidden" id="userID" name="userID" value="@item.userID"/>
                                            <input type="hidden" id="gameID" name="gameID" value="@item.gameID"/>
                                        <input class="btn btn-add-to-wishlist" type="submit" value="Approve this review" />
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                    </div>                
            }
        }
        else
        {
            foreach (Rating item in (List<Rating>)ViewData["RatingList"])
            {
                //If user is logged in but not an admin, only show approved reviews
                if(item.approved == 1)
                { 
            <div class="row">
                <div class="col-md-8">
                    <div class="panel panel-default panel-center">
                        <div class="panel-heading">
                            <a href="@Url.Action("Details", "CVGSUsers", new { id = item.CVGSUser.userID})">
                                <h3 class="panel-title">@item.CVGSUser.userName</h3>
                            </a>
                        </div>
                        <div class="panel-body">
                            Rating: @item.rating1/10
                            @if (item.review != null)
                            {
                                <br />
                                @item.review
                            }
                            
                        </div>
                    </div>
                </div>
            </div>
    }
            
            }
        }
     }